- hosts: test2_hosts
#  user: xxxxxxx
#  become: yes
#  become_user: xyz
#  sudo: yes
  ignore_errors: True
  gather_facts: no
  tasks:
   - name: copy folder from test1_hosts to test2_hosts
     synchronize:
       src=/ngs/app/gbid/java-1.7.0.rpm
       dest=/tmp/java-1.7.0.rpm
      # mode=pull
     delegate_to: test1_hosts
     

