# Example playbook for get_url module
--- # Fetch module Example
- hosts: test2_hosts
  user: xxxxxx
  sudo: yes
  #become_user: xyz
  connection: ssh
  ignore_errors: true
  tasks:
    - name: Download a file abc.yml
      get_url:
        url: http://abcd.com/path/abc.yml
        dest: /etc/abc.yml
        mode: 0440

    - name: Download file and force basic authentication
      get_url:
        url: http://abcd.com/path/abc.yml
        dest: /etc/foo.conf
        force_basic_auth: yes

    - name: Download file with custom HTTP headers information
      get_url:
        url: http://abcd.com/path/abc.yml
        dest: /etc/abc.yml
        headers: 'key:value,key:value'

    - name: Download a file with checksum (sha256)
      get_url:
        url: http://abcd.com/path/abc.yml
        dest: /etc/abc.yml
        checksum: sha256:b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c

    - name: Download file with checksum (md5)
      get_url:
        url: http://abcd.com/path/abc.yml
        dest: /etc/abc.yml
        checksum: md5:66dffb5228a211e61d6d7ef4a86f5758

    - name: Download file from a file path
      get_url:
        url: file:///tmp/abc.yml
        dest: /tmp/afilecopy.yml
 
