--- # Lineinfile module Example
- hosts: test2_hosts
  user: {{ a_user }}
  sudo: yes
  become_user: {{ b_user }}
  connection: ssh
  ignore_errors: false
  tasks:
    - name: Update a line in a file with regex match
      lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.0\.1'
        line: '127.0.0.1 localhost'
        owner: root
        group: root
        mode: 0644
       
    - name: Update in a next line in a file where regex matches
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen '
        insertafter: '^#Listen '
        line: 'Listen 8080'
        #state: present
