--- # Stats module Example
- hosts: test2_hosts
  user: xxxxxx
  sudo: yes
#  become_user: xyz
  connection: ssh
  ignore_errors: true
  tasks:
    - name: Check weather file exists or not in User_Home
      stat:
        path: $HOME/abc.txt
      register: stat_output

    - name: Create a file, if file doesn't exist already
      file:
        path: $HOME/abc.txt
        state: touch
        owner: xxxxx
        group: xxxxx
        mode: 0644
      when: stat_output.stat.exists == False 
# Check the existance of a directory
    - stat: path=/path/to/directory
      register: p
# Debug to print if directory exists
    - debug: msg="Path exists and is a directory"
      when: p.stat.isdir is defined and p.stat.isdir
